---
name: spellcheck

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.0.1
        with:
          files: "**/*"
